import { afterEach, describe, expect, test } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { harnessesOnPath } from "./fixtures.test-support";
import { flatten, generatedPath, installRules, planRules } from "./rules";

const roots: string[] = [];

function home(): string {
  const root = mkdtempSync(join(tmpdir(), "dim-rules-"));
  roots.push(root);
  mkdirSync(join(root, ".claude"), { recursive: true });
  mkdirSync(join(root, ".codex"), { recursive: true });
  return root;
}

function withCodex(root: string): { HOME: string; PATH: string } {
  return { HOME: root, PATH: harnessesOnPath(root, ["codex"]) };
}

afterEach(() => {
  while (roots.length > 0) rmSync(roots.pop() as string, { recursive: true, force: true });
});

describe("flatten", () => {
  test("resolves a relative import against the target tool's own directory", () => {
    const root = home();
    writeFileSync(join(root, ".claude", "RTK.md"), "claude flavour");
    writeFileSync(join(root, ".codex", "RTK.md"), "codex flavour");

    expect(flatten("@RTK.md", join(root, ".codex"))).toBe("codex flavour");
    expect(flatten("@RTK.md", join(root, ".claude"))).toBe("claude flavour");
  });

  test("keeps an absolute import pointing where it points", () => {
    const root = home();
    const path = join(root, "shared.md");
    writeFileSync(path, "shared body");
    expect(flatten(`@${path}`, join(root, ".codex"))).toBe("shared body");
  });

  test("says so in the file when an import cannot be resolved", () => {
    const root = home();
    expect(flatten("@nope.md", join(root, ".codex"))).toContain("not found for this tool");
  });

  test("expands nested imports until it reaches their content", () => {
    const root = home();
    const dir = join(root, ".codex");
    for (let index = 0; index < 6; index += 1) {
      writeFileSync(join(dir, `${index}.md`), index === 5 ? "deep rule" : `@${index + 1}.md`);
    }
    expect(flatten("@0.md", dir)).toBe("deep rule");
  });

  test("reports a cycle instead of emitting an unresolved import", () => {
    const root = home();
    const dir = join(root, ".codex");
    writeFileSync(join(dir, "first.md"), "@second.md");
    writeFileSync(join(dir, "second.md"), "@first.md");
    expect(() => flatten("@first.md", dir)).toThrow("rules import cycle");
  });

  test("leaves ordinary text alone, including an address mid-line", () => {
    expect(flatten("mail me @ home", "/tmp")).toBe("mail me @ home");
    expect(flatten("# Heading\n\nbody", "/tmp")).toBe("# Heading\n\nbody");
  });
});

describe("install", () => {
  test("writes the flattened rules and reports staleness afterwards", () => {
    const root = home();
    writeFileSync(join(root, ".claude", "RTK.md"), "tool bits");
    writeFileSync(join(root, ".codex", "RTK.md"), "codex bits");
    writeFileSync(join(root, ".claude", "CLAUDE.md"), "@RTK.md\n\nno hacks");
    const env = withCodex(root);

    expect(planRules(env).state).toBe("absent");
    installRules(env);

    const written = readFileSync(generatedPath(env), "utf8");
    expect(written).toContain("codex bits");
    expect(written).not.toContain("tool bits");
    expect(written).toContain("no hacks");
    expect(written).toContain("Generated by");
    expect(planRules(env).state).toBe("unchanged");

    writeFileSync(join(root, ".claude", "CLAUDE.md"), "@RTK.md\n\nno hacks, and no flags");
    expect(planRules(env).state).toBe("stale");
  });

  test("keeps what it overwrites, which may be the only copy", () => {
    const root = home();
    writeFileSync(join(root, ".claude", "CLAUDE.md"), "canonical");
    writeFileSync(join(root, ".codex", "AGENTS.md"), "something the owner wrote");
    const env = withCodex(root);

    installRules(env);
    expect(readFileSync(`${generatedPath(env)}.dim-backup`, "utf8")).toBe("something the owner wrote");
    writeFileSync(join(root, ".claude", "CLAUDE.md"), "revised canonical");
    installRules(env);
    expect(readFileSync(`${generatedPath(env)}.dim-backup`, "utf8")).toBe("something the owner wrote");
    expect(readFileSync(`${generatedPath(env)}.dim-backup-2`, "utf8")).toContain("canonical");
  });

  test("reports the backup made by each install command", () => {
    const root = home();
    const source = join(root, ".claude", "CLAUDE.md");
    const target = generatedPath({ HOME: root });
    writeFileSync(source, "canonical");
    writeFileSync(target, "owner rules");
    const run = () => {
      const child = Bun.spawnSync([process.execPath, join(import.meta.dir, "cli.ts"), "rules", "install"], {
        env: {
          ...process.env,
          HOME: root,
          PATH: `${harnessesOnPath(root, ["codex"])}:${process.env.PATH}`,
        },
        stdout: "pipe",
        stderr: "pipe",
      });
      expect(child.exitCode).toBe(0);
      return JSON.parse(child.stdout.toString()).result.backup;
    };
    expect(run()).toBe(`${target}.dim-backup`);
    writeFileSync(source, "revised canonical");
    expect(run()).toBe(`${target}.dim-backup-2`);
  });

  test("writes no codex rules where codex is not installed", () => {
    const root = home();
    writeFileSync(join(root, ".claude", "CLAUDE.md"), "canonical");
    const env = { HOME: root, PATH: harnessesOnPath(root, ["claude"]) };

    expect(planRules(env).state).toBe("not-installed");
    installRules(env);
    expect(existsSync(generatedPath(env))).toBe(false);
  });

  test("does nothing when there is no canonical file to flatten", () => {
    const env = withCodex(home());
    expect(planRules(env).state).toBe("missing-source");
    installRules(env);
    expect(planRules(env).state).toBe("missing-source");
  });
});
