import { afterEach, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { flatten, generatedPath, installRules, planRules } from "./rules";

const roots: string[] = [];

function home(): string {
  const root = mkdtempSync(join(tmpdir(), "dim-rules-"));
  roots.push(root);
  mkdirSync(join(root, ".claude"), { recursive: true });
  mkdirSync(join(root, ".codex"), { recursive: true });
  return root;
}

afterEach(() => {
  while (roots.length > 0) rmSync(roots.pop() as string, { recursive: true, force: true });
});

describe("flatten", () => {
  test("resolves a relative import against the target tool's own directory", () => {
    const root = home();
    writeFileSync(join(root, ".claude", "RTK.md"), "claude flavour");
    writeFileSync(join(root, ".codex", "RTK.md"), "codex flavour");

    // The two files differ on purpose, so picking the source tool's copy would
    // silently ship Claude's wording to Codex.
    expect(flatten("@RTK.md", join(root, ".codex"))).toBe("codex flavour");
    expect(flatten("@RTK.md", join(root, ".claude"))).toBe("claude flavour");
  });

  test("keeps an absolute import pointing where it points", () => {
    const root = home();
    const path = join(root, "shared.md");
    writeFileSync(path, "shared body");
    expect(flatten(`@${path}`, join(root, ".codex"))).toBe("shared body");
  });

  test("says so in the file when an import cannot be resolved", () => {
    const root = home();
    // Dropping the line would leave a rules file that looks complete and is not.
    expect(flatten("@nope.md", join(root, ".codex"))).toContain("not found for this tool");
  });

  test("leaves ordinary text alone, including an address mid-line", () => {
    expect(flatten("mail me @ home", "/tmp")).toBe("mail me @ home");
    expect(flatten("# Heading\n\nbody", "/tmp")).toBe("# Heading\n\nbody");
  });
});

describe("install", () => {
  test("writes the flattened rules and reports staleness afterwards", () => {
    const root = home();
    writeFileSync(join(root, ".claude", "RTK.md"), "tool bits");
    writeFileSync(join(root, ".codex", "RTK.md"), "codex bits");
    writeFileSync(join(root, ".claude", "CLAUDE.md"), "@RTK.md\n\nno hacks");
    const env = { HOME: root };

    expect(planRules(env).state).toBe("absent");
    installRules(env);

    const written = readFileSync(generatedPath(env), "utf8");
    expect(written).toContain("codex bits");
    expect(written).not.toContain("tool bits");
    expect(written).toContain("no hacks");
    expect(written).toContain("Generated by");
    expect(planRules(env).state).toBe("unchanged");

    writeFileSync(join(root, ".claude", "CLAUDE.md"), "@RTK.md\n\nno hacks, and no flags");
    expect(planRules(env).state).toBe("stale");
  });

  test("keeps what it overwrites, which may be the only copy", () => {
    const root = home();
    writeFileSync(join(root, ".claude", "CLAUDE.md"), "canonical");
    writeFileSync(join(root, ".codex", "AGENTS.md"), "something the owner wrote");
    const env = { HOME: root };

    installRules(env);
    expect(readFileSync(`${generatedPath(env)}.dim-backup`, "utf8")).toBe("something the owner wrote");
  });

  test("does nothing when there is no canonical file to flatten", () => {
    const env = { HOME: home() };
    expect(planRules(env).state).toBe("missing-source");
    installRules(env);
    expect(planRules(env).state).toBe("missing-source");
  });
});
