import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join } from "node:path";
import { type Env, resolveHomeDir } from "./paths";

/**
 * Claude Code expands `@path` imports in its rules file; Codex does not — a
 * sentinel placed behind an import reached Claude and never reached Codex, so
 * `~/.codex/AGENTS.md` has been delivering its import line as literal text. The
 * conventions therefore have to arrive already flattened.
 */
export const CANONICAL = [".claude", "CLAUDE.md"];
export const GENERATED = [".codex", "AGENTS.md"];

const HEADER = "<!-- Generated by `dim install-rules` from ~/.claude/CLAUDE.md. Edit that file. -->";
const MAX_DEPTH = 4;

export function canonicalPath(env: Env = process.env): string {
  return join(resolveHomeDir(env), ...CANONICAL);
}

export function generatedPath(env: Env = process.env): string {
  return join(resolveHomeDir(env), ...GENERATED);
}

/**
 * A relative import resolves against the *target* tool's directory, so `@RTK.md`
 * in the canonical file picks up `~/.codex/RTK.md` when generating for Codex.
 * The two RTK files differ on purpose — Codex's carries a rule about prefixing
 * shell commands — and flattening the wrong one would quietly swap that out.
 */
export function flatten(text: string, targetDir: string, depth = 0): string {
  if (depth >= MAX_DEPTH) return text;
  return text
    .split("\n")
    .map((line) => {
      const match = /^@(\S+)\s*$/.exec(line);
      if (!match?.[1]) return line;
      const ref = match[1];
      const path = isAbsolute(ref) ? ref : join(targetDir, ref);
      if (!existsSync(path)) return `<!-- dim: ${ref} not found for this tool -->`;
      return flatten(readFileSync(path, "utf8").trimEnd(), dirname(path), depth + 1);
    })
    .join("\n");
}

export type RulesPlan = {
  source: string;
  path: string;
  contents: string;
  state: "missing-source" | "unchanged" | "stale" | "absent";
};

export function planRules(env: Env = process.env): RulesPlan {
  const source = canonicalPath(env);
  const path = generatedPath(env);
  if (!existsSync(source)) {
    return { source, path, contents: "", state: "missing-source" };
  }
  const body = flatten(readFileSync(source, "utf8").trimEnd(), dirname(path));
  const contents = `${HEADER}\n\n${body}\n`;
  if (!existsSync(path)) return { source, path, contents, state: "absent" };
  return {
    source,
    path,
    contents,
    state: readFileSync(path, "utf8") === contents ? "unchanged" : "stale",
  };
}

export function installRules(env: Env = process.env): RulesPlan {
  const plan = planRules(env);
  if (plan.state === "unchanged" || plan.state === "missing-source") return plan;
  mkdirSync(dirname(plan.path), { recursive: true });
  // The file being replaced may be the only copy of a rule the owner wrote by
  // hand, and this command overwrites it wholesale.
  if (existsSync(plan.path)) copyFileSync(plan.path, `${plan.path}.dim-backup`);
  writeFileSync(plan.path, plan.contents);
  return plan;
}
