import { existsSync, mkdirSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join } from "node:path";
import { refuser } from "./coded-error";
import { copyBackup } from "./file-backup";
import { harnessInstalled } from "./harness-installed";
import { type Env, resolveHomeDir } from "./paths";

const refuseRules = refuser<{ readonly rules_import_cycle: { readonly path: string } }>({
  rules_import_cycle: {
    message: ({ path }) => `rules import cycle at ${path}`,
    resolve: ({ path }) => `remove the @-import of ${path} that leads back to itself`,
  },
});

export const CANONICAL = [".claude", "CLAUDE.md"];
export const GENERATED = [".codex", "AGENTS.md"];

const HEADER = "<!-- Generated by `dim rules install` from ~/.claude/CLAUDE.md. Edit that file. -->";

export function canonicalPath(env: Env = process.env): string {
  return join(resolveHomeDir(env), ...CANONICAL);
}

export function generatedPath(env: Env = process.env): string {
  return join(resolveHomeDir(env), ...GENERATED);
}

function expand(text: string, targetDir: string, active: Set<string>): string {
  return text
    .split("\n")
    .map((line) => {
      const match = /^@(\S+)\s*$/.exec(line);
      if (!match?.[1]) return line;
      const ref = match[1];
      const path = isAbsolute(ref) ? ref : join(targetDir, ref);
      if (!existsSync(path)) return `<!-- dim: ${ref} not found for this tool -->`;
      const resolved = realpathSync(path);
      if (active.has(resolved)) throw refuseRules("rules_import_cycle", { path });
      active.add(resolved);
      try {
        return expand(readFileSync(path, "utf8").trimEnd(), dirname(path), active);
      } finally {
        active.delete(resolved);
      }
    })
    .join("\n");
}

export function flatten(text: string, targetDir: string): string {
  return expand(text, targetDir, new Set());
}

export type RulesPlan = {
  source: string;
  path: string;
  contents: string;
  state: "not-installed" | "missing-source" | "unchanged" | "stale" | "absent";
};

export function planRules(env: Env = process.env): RulesPlan {
  const source = canonicalPath(env);
  const path = generatedPath(env);
  if (!harnessInstalled("codex", env)) return { source, path, contents: "", state: "not-installed" };
  if (!existsSync(source)) {
    return { source, path, contents: "", state: "missing-source" };
  }
  const body = flatten(readFileSync(source, "utf8").trimEnd(), dirname(path));
  const contents = `${HEADER}\n\n${body}\n`;
  if (!existsSync(path)) return { source, path, contents, state: "absent" };
  return {
    source,
    path,
    contents,
    state: readFileSync(path, "utf8") === contents ? "unchanged" : "stale",
  };
}

export function installRules(env: Env = process.env): RulesPlan & { backup?: string | null } {
  const plan = planRules(env);
  if (plan.state === "unchanged" || plan.state === "missing-source" || plan.state === "not-installed") {
    return plan;
  }
  mkdirSync(dirname(plan.path), { recursive: true });
  const backup = existsSync(plan.path) ? copyBackup(plan.path) : null;
  writeFileSync(plan.path, plan.contents);
  return { ...plan, backup };
}
