/**
 * What a factory worker is called: `nut-73`, `capacitor-8`.
 *
 * A word and a number rather than a written-out list of names, because a pair drawn from a
 * list and a range is as many names as anyone will ever need, where a list of finished
 * names is as long as it is. The factory issues the name, so it is the identity every
 * moment holds rather than a label over one.
 *
 * The vocabulary is a factory's — materials, signals and parts — so a worker never reads as
 * a person and never borrows a name from somewhere a reader has to recognize.
 */

import { randomInt } from "node:crypto";

const WORDS = [
  "nut",
  "bolt",
  "washer",
  "rivet",
  "screw",
  "stud",
  "pin",
  "dowel",
  "clamp",
  "bracket",
  "flange",
  "gasket",
  "seal",
  "bushing",
  "bearing",
  "collar",
  "sleeve",
  "shim",
  "spring",
  "latch",
  "hinge",
  "hook",
  "anchor",
  "clevis",
  "cotter",
  "staple",
  "eyelet",
  "ferrule",
  "grommet",
  "fastener",
  "tab",
  "clip",
  "gear",
  "cog",
  "sprocket",
  "pulley",
  "belt",
  "chain",
  "cam",
  "shaft",
  "axle",
  "spindle",
  "rotor",
  "stator",
  "piston",
  "cylinder",
  "valve",
  "nozzle",
  "pump",
  "impeller",
  "turbine",
  "motor",
  "engine",
  "gearbox",
  "crank",
  "flywheel",
  "ratchet",
  "pawl",
  "lever",
  "plunger",
  "actuator",
  "solenoid",
  "diaphragm",
  "manifold",
  "lathe",
  "drill",
  "mill",
  "press",
  "forge",
  "kiln",
  "welder",
  "cutter",
  "grinder",
  "planer",
  "router",
  "shear",
  "punch",
  "die",
  "vise",
  "hammer",
  "mallet",
  "chisel",
  "rasp",
  "file",
  "saw",
  "blade",
  "bit",
  "auger",
  "wrench",
  "socket",
  "torque",
  "caliper",
  "reamer",
  "broach",
  "mandrel",
  "jointer",
  "capacitor",
  "resistor",
  "diode",
  "transistor",
  "inductor",
  "transformer",
  "relay",
  "switch",
  "sensor",
  "terminal",
  "conductor",
  "insulator",
  "oscillator",
  "circuit",
  "battery",
  "anode",
  "cathode",
  "filament",
  "coil",
  "magnet",
  "antenna",
  "encoder",
  "fuse",
  "connector",
  "rectifier",
  "inverter",
  "regulator",
  "generator",
  "controller",
  "contactor",
  "potentiometer",
  "thermistor",
  "photodiode",
  "breadboard",
  "busbar",
  "copper",
  "bronze",
  "brass",
  "nickel",
  "cobalt",
  "iron",
  "steel",
  "carbon",
  "alloy",
  "zinc",
  "tin",
  "lead",
  "silver",
  "titanium",
  "tungsten",
  "chrome",
  "graphite",
  "ceramic",
  "rubber",
  "nylon",
  "polymer",
  "resin",
  "silicon",
  "quartz",
  "glass",
  "fiber",
  "cement",
  "powder",
  "epoxy",
  "enamel",
  "hopper",
  "bin",
  "tray",
  "crate",
  "pallet",
  "reel",
  "spool",
  "drum",
  "conveyor",
  "gantry",
  "hoist",
  "crane",
  "trolley",
  "cart",
  "wagon",
  "loader",
  "feeder",
  "sorter",
  "lifter",
  "stacker",
  "carrier",
  "shuttle",
  "rack",
  "shelf",
  "silo",
  "tank",
  "vat",
  "vessel",
  "chute",
  "filter",
  "screen",
  "mesh",
  "grate",
  "sander",
  "shaper",
  "mixer",
  "extruder",
  "foundry",
  "mold",
  "casting",
  "winder",
  "coiler",
  "compressor",
  "boiler",
  "radiator",
  "reservoir",
  "pipeline",
  "coupler",
  "coupling",
  "hub",
  "barrel",
  "fixture",
  "jig",
  "clutch",
  "throttle",
  "thermostat",
  "workbench",
  "gauge",
  "meter",
  "probe",
  "scanner",
  "reader",
  "tester",
  "level",
  "scale",
  "ruler",
  "compass",
  "template",
  "stencil",
  "beacon",
  "signal",
  "marker",
  "label",
  "ticket",
  "ledger",
  "alarm",
  "siren",
  "flare",
  "lamp",
  "helmet",
  "glove",
  "apron",
  "shield",
  "guard",
  "barrier",
  "rail",
  "vent",
  "duct",
  "fan",
  "cooler",
  "heater",
  "purifier",
  "exhaust",
  "brake",
  "damper",
] as const;

const NUMBERS = 100;

/** Every name the vocabulary can issue, which is what a draw picks from. */
export const WORKER_NAMES: readonly string[] = WORDS.flatMap((word) =>
  Array.from({ length: NUMBERS }, (_, number) => `${word}-${number}`),
);

/**
 * A name drawn at random from the ones nothing holds. Chosen from the free names rather
 * than retried until a draw misses the held ones, so it neither collides nor slows as the
 * space fills, and a name says nothing about the order its holder was issued in.
 *
 * `pick` returns an index below the count it is given; a test passes its own to read the
 * draw off a known position.
 */
export function randomWorkerName(taken: ReadonlySet<string>, pick = randomInt): string {
  const free = WORKER_NAMES.filter((name) => !taken.has(name));
  if (free.length === 0)
    throw new Error(
      `every one of the ${WORKER_NAMES.length} worker names is held; the word list in ` +
        "src/worker-name.ts is what widens the vocabulary",
    );
  return free[pick(free.length)] as string;
}
