/**
 * What a factory worker is called: `copper-73`, `relay-8`.
 *
 * A word and a number rather than a written-out list of names, because a pair drawn from a
 * list and a range is as many names as anyone will ever need, where a list of finished
 * names is as long as it is. The factory issues the name, so it is the identity every
 * moment holds rather than a label over one.
 *
 * The vocabulary is a factory's — materials, signals and parts — so a worker never reads as
 * a person and never borrows a name from somewhere a reader has to recognize.
 */

import { randomInt } from "node:crypto";

const WORDS = [
  "copper",
  "relay",
  "amber",
  "vector",
  "anvil",
  "cobalt",
  "spindle",
  "quartz",
  "piston",
  "beacon",
  "nickel",
  "girder",
  "signal",
  "pewter",
  "lattice",
  "carbon",
  "magnet",
  "bronze",
  "ratchet",
  "circuit",
  "granite",
  "flange",
  "silver",
  "torque",
  "bellows",
  "cinder",
  "dynamo",
  "ferrite",
  "gasket",
  "hammer",
  "indigo",
  "jasper",
  "kelvin",
  "lumen",
  "mortar",
  "nitrate",
  "onyx",
  "plasma",
  "quarry",
  "rivet",
  "solder",
  "tungsten",
  "umber",
  "valve",
  "wedge",
  "zinc",
  "alloy",
  "bracket",
  "chisel",
  "damper",
  "ember",
  "filament",
  "gauge",
  "hinge",
  "ingot",
  "joule",
  "keystone",
  "ledger",
  "mantle",
  "nozzle",
  "octane",
  "pulley",
  "quill",
  "rotor",
  "shuttle",
  "trestle",
  "updraft",
  "vernier",
  "winch",
  "axle",
  "ballast",
  "caliper",
  "drill",
  "engine",
  "forge",
  "gantry",
  "harrow",
  "impulse",
  "jacket",
  "kiln",
  "lever",
  "mandrel",
  "notch",
  "oxide",
  "pylon",
  "quench",
  "ridge",
  "spar",
  "tether",
  "union",
  "vise",
  "warden",
  "yoke",
  "zephyr",
  "auger",
  "bobbin",
  "clamp",
  "dowel",
  "etcher",
  "ferrule",
  "grommet",
  "husk",
  "iris",
  "jetty",
  "knuckle",
  "lathe",
  "mallet",
  "nutmeg",
  "oarlock",
  "pinion",
  "quiver",
  "rasp",
  "sickle",
  "tongs",
  "ulster",
  "vellum",
  "wicket",
  "yarrow",
  "zircon",
  "arbor",
  "bushing",
  "collet",
  "detent",
  "eyelet",
  "fulcrum",
  "gimbal",
  "hopper",
  "idler",
  "journal",
  "keeper",
  "linkage",
  "mortise",
  "needle",
  "offset",
  "packing",
  "quadrant",
  "reamer",
  "sleeve",
  "tappet",
  "upright",
  "verge",
  "washer",
  "xenon",
  "yardarm",
  "bracer",
  "cotter",
  "dovetail",
  "escutcheon",
  "fillet",
  "gudgeon",
  "hasp",
  "inlay",
  "jamb",
  "kerf",
  "lintel",
  "muntin",
  "newel",
  "ogee",
  "purlin",
  "quoin",
  "rafter",
  "sill",
  "tenon",
  "undercut",
  "veneer",
  "wainscot",
  "abutment",
  "batten",
  "corbel",
  "dentil",
  "eaves",
  "finial",
  "gable",
  "header",
  "joist",
  "keel",
  "louver",
  "molding",
  "nosing",
  "oriel",
  "parapet",
  "quirk",
  "reveal",
  "soffit",
  "transom",
  "valance",
  "welt",
  "apron",
  "baluster",
  "capital",
  "drip",
  "fascia",
  "girt",
  "haunch",
  "impost",
  "jetting",
  "kicker",
  "lagging",
  "muller",
  "nogging",
  "plinth",
  "quarter",
  "riser",
  "stringer",
  "tread",
  "voussoir",
  "wythe",
  "arris",
  "bolster",
  "chamfer",
  "dado",
  "edging",
  "flashing",
  "groove",
  "hood",
  "inset",
  "jointer",
  "knap",
  "lacing",
  "miter",
  "nib",
  "ovolo",
  "pilaster",
  "rebate",
  "scarf",
  "tracery",
  "volute",
  "whorl",
  "astragal",
  "bevel",
  "cavetto",
  "torus",
  "cyma",
  "echinus",
  "fluting",
  "guilloche",
  "helix",
  "listel",
  "meander",
  "nodule",
  "pendant",
  "reglet",
  "scotia",
  "trefoil",
  "vermicule",
  "annulet",
  "bead",
  "cable",
  "diaper",
  "fretwork",
  "godroon",
  "imbrex",
  "lozenge",
  "medallion",
  "paterae",
  "rondel",
] as const;

const NUMBERS = 100;

/** Every name the vocabulary can issue, which is what a draw picks from. */
export const WORKER_NAMES: readonly string[] = WORDS.flatMap((word) =>
  Array.from({ length: NUMBERS }, (_, number) => `${word}-${number}`),
);

/**
 * A name drawn at random from the ones nothing holds. Chosen from the free names rather
 * than retried until a draw misses the held ones, so it neither collides nor slows as the
 * space fills, and a name says nothing about the order its holder was issued in.
 *
 * `pick` returns an index below the count it is given; a test passes its own to read the
 * draw off a known position.
 */
export function randomWorkerName(taken: ReadonlySet<string>, pick = randomInt): string {
  const free = WORKER_NAMES.filter((name) => !taken.has(name));
  if (free.length === 0)
    throw new Error(
      `every one of the ${WORKER_NAMES.length} worker names is held; the word list in ` +
        "src/worker-name.ts is what widens the vocabulary",
    );
  return free[pick(free.length)] as string;
}
